name: red-tetris

services:
  react:
    container_name: react
    build:
      context: ./hypertube-front
      dockerfile: Dockerfile
    image: react
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - ./hypertube-front:/app
      - /app/node_modules
    networks:
      - main

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend
    env_file:
      - .env
    ports:
      - '5555:5555'
      - '${BACKEND_PORT}:${BACKEND_PORT}'
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - main
    depends_on:
      - postgres
    

  postgres:
    image: postgres:17.0-alpine3.20
    container_name: postgres
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - main

volumes:
  postgres:
    name: postgres-volume

networks:
  main:
